### ISSUE TITLE
gatsby-image-background-slider seem not to work for me

### ISSUE THREAD

**Issue by kelvinsekx** [GabeEddyT/gatsby-image-background-slider#10]
I need help, do I need to install gatsby-image and sharp plugin myself ?

Can't resolve 'gatsby-image' in 'C:\Users\kelvin\sharpview\node_modules\gatsby-image-background-slider\dist'

If you're trying to use a package make sure that 'gatsby-image' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules\gatsby-image-background-slider\dist\index.es.js

**Comment by GabeEddyT** [comment]
Yes, you need gatsby-image. Although, if your project isn't already using gatsby-image—and you don't anticipate using it—you can just use [react-background-slider](https://www.npmjs.com/package/react-background-slider) to avoid the dependency.

**Comment by kelvinsekx** [comment]
It worked well now. Thanks
