### ISSUE TITLE
Set loading to eager?

### ISSUE THREAD

**Issue by david-mateogit** [GabeEddyT/gatsby-image-background-slider#2]
Hello.
Sorry as this is not the essence of the plugin but can we get a prop to set the loading to "eager".

That way Gatsby Img loads the images right away.

I have a hero section with a slider and it takes a while to show the images.
I used react background slider but that doesn't use the img optimizations from gatsby.

Let me know if there is a setting for that or if it could be possible to implement.

Thanks for the nice plugin.

**Comment by GabeEddyT** [comment]
Any properties that don't belong to the `BackgroundSlider` class are spread onto the `Img` elements themselves so 

```jsx
<BackgroundSlider
// ...
loading={"eager"}				
>
```

is akin to 

```jsx
<Img fluid={data.childImageSharp.fluid} /* ... */ loading={"eager"}/>
```

which should result in the desired behavior. I acknowledge I could've documented this better. Or at all for that matter.

**Comment by david-mateogit** [comment]
Thanks a lot.
