### ISSUE TITLE
Not able to define query outside BackgroundSlider and use within the element.

### ISSUE THREAD

**Issue by ajayshanmuganathan** [GabeEddyT/gatsby-image-background-slider#3]
Hi,
 I'm pretty new to gatsby / React / GraphQL, and i'm working my way through creating a site as a side project. So I wanted to have an image slider in my site and used this plugin. Found that only if we pass the query in the BackgroundSlider element as a staticQuery in my index page, I'm able to get the slider working.

If I define the query outside and then refer the query prop in BackgroundSlider to the data prop, or if I define the same BackgroundSlider as a separate component and import and use in the index page, it doesnt work and throws a  TypeError: Cannot read property 'nodes' of undefined.

**Is there any way to define the query outside the backgroundslider element?**

Not Working:

import React from "react"
import { Link ,graphql, useStaticQuery} from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

import Background from "../components/global/Background"
import Info from "../components/Home/Info"
import Slider from "../components/Home/Slider"
import BackgroundSlider from "gatsby-image-background-slider"
import Characteristics from "../components/Home/Characteristics"

const IndexPage = ({data}) => (
  <Layout>
    <SEO title="Home" />
    
      <div className="default-background">
            <div className="container">   
                  <BackgroundSlider 
                    query = {data.backgrounds}
                    initDelay={2}
                    transition={4}
                    duration={5}
                    images={["kitchen1.jpg","kitchen.jpeg","preethi.jpeg", "butterfly.jpg"]}
                    style={{
                      top: "105px",
                      maxHeight: "50vh",
                      backgroundSize: "cover",
                      backgroundPosition: "center"
                    }}  />
                      <h1 className="heroheader title text-white text-center text-uppercase display-4 font-weight-bold ">Avinash Industries</h1>
                      <p className="col-10 col-sm-8 mx-auto text-center eggwhite" > We are Original Equipment Manufacturers (OEM) building high-quality products for the leading kitchen appliance brands in the nation.</p>
              </div>   
          </div>
      
    
    <Info/>
    <Info/> 
    
  </Layout>

  
)

**export const query = graphql`
{
  backgrounds: allFile(filter: {sourceInstanceName: {eq: "images"}}) {
    nodes{
      relativePath
      childImageSharp {
        fluid(maxWidth: 2000, quality: 100) {
          ...GatsbyImageSharpFluid_withWebp
        }
      }
    }
  }
}`;**

export default IndexPage

Error Thrown:
×
TypeError: Cannot read property 'nodes' of undefined
_loop
src/index.js:39
  36 | 
  37 | if(images){
  38 | 	for(let image of images){
> 39 | 		nodes.safePush(
  40 | 			query.backgrounds.nodes.find(
  41 | 				node => node.relativePath === image
  42 | 			)
View compiled
BackgroundSlider
src/index.js:38
  35 | }
  36 | 
  37 | if(images){
> 38 | 	for(let image of images){
  39 | 		nodes.safePush(
  40 | 			query.backgrounds.nodes.find(
  41 | 				node => node.relativePath === image
View compiled
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:16259
  16256 |   }
  16257 | }
  16258 | 
> 16259 | var children = Component(props, refOrContext);
  16260 | 
  16261 | if (didScheduleRenderPhaseUpdate) {
  16262 |   do {
View compiled

**Comment by GabeEddyT** [comment]
Try using just the object, `data`, rather than `data.backgrounds` when
assigning to query.

**Comment by GabeEddyT** [comment]
As an example, this is what I have on my own site:
```jsx
const query = useStaticQuery(graphql`
  query {
    backgrounds: allFile (filter: {sourceInstanceName: {eq: "backgrounds"}}){
      nodes {
        relativePath
        childImageSharp {
          fluid (maxWidth: 4000, quality: 100){
            ...GatsbyImageSharpFluid_withWebp_tracedSVG
          }
        }
      }
    }
  }
`)

// ...

return(
  <> 
    <Layout>
      <SEO title="Home"/>
      <div style={{zIndex:-3}}>
        <BackgroundSlider 
        callbacks = {setBg}
        images={["stray-manta.jpg", "stray-gameplay-1.png", "stray-poster.png", "ukulele.jpg", "ukulele-gameplay.png", "super-sibling-smash.png", "gtar.png", "stray-splash.png"]}
        initDelay={12}
        transition={3}
        duration={7}
        query={query}
        backgroundColor={true}	
        >
```
So changing your code to 
```jsx
 <div className="default-background">
        <div className="container">   
              <BackgroundSlider 
                query = {data} // not `data.backgrounds`
                initDelay={2}
                transition={4}
                duration={5}
                images={["kitchen1.jpg","kitchen.jpeg","preethi.jpeg", "butterfly.jpg"]}
                style={{
                  top: "105px",
                  maxHeight: "50vh",
                  backgroundSize: "cover",
                  backgroundPosition: "center"
                }}  />
                  <h1 className="heroheader title text-white text-center text-uppercase display-4 font-weight-bold ">Avinash Industries</h1>
                  <p className="col-10 col-sm-8 mx-auto text-center eggwhite" > We are Original Equipment Manufacturers (OEM) building high-quality products for the leading kitchen appliance brands in the nation.</p>
          </div>   
      </div>
  

<Info/>
<Info/> 
```
should result in the behavior you desire.

If you'll notice the error message, it's trying to access the property `backgrounds` on the `data.backgrounds` you passed in. Essentially `data.backgrounds.backgrounds`, which is not defined.
