### ISSUE TITLE
Cannot read property 'onChange' of undefined

### ISSUE THREAD

**Issue by ggbellotti** [GabeEddyT/gatsby-image-background-slider#6]
Hi guys!
Congratulations for the excellent work and dedication to the project. The plugins that Gatsby have helps us a lot.

I would like to understand and resolve this error. I tried in different ways solve, but I couldn't ...

![Cannot read property 'onChange' of undefined](https://iili.io/da4qHN.png)

Basically the site starts and loads the image. However, when moving to the second image, this error occurs.

Code:
```javascript
import { graphql, useStaticQuery } from "gatsby"

import BackgroundSlider from "gatsby-image-background-slider"
import React from "react"

const BgSlider = () => {
  const query = useStaticQuery(graphql`
    query {
      backgrounds: allFile(
        filter: { sourceInstanceName: { eq: "backgrounds" } }
      ) {
        nodes {
          relativePath
          childImageSharp {
            fluid(maxWidth: 4000, quality: 100) {
              ...GatsbyImageSharpFluid_withWebp_tracedSVG
            }
          }
        }
      }
    }
  `)
  return (
    <BackgroundSlider
      initDelay={3}
      transition={3}
      duration={3}
      query={query}
    />
  )
}
export default BgSlider

```
There is no error in the terminal, neither of the compilation.

Version plugin: gatsby-image-background-slider: "^0.0.3",

**Comment by epg323** [comment]
i'm having the same issue

**Comment by epg323** [comment]
Just fixed it. Shoot me a message @guilhermebellotti , if you need help fixing it.

**Comment by ggbellotti** [comment]
Hey @epg323 ! How did you get it fixed? I did not get it yet :(

**Comment by epg323** [comment]
@guilhermebellotti 

Go to node_modules> gatsby-image-background-slider> dist> index.js

look for "callbacks.onChange" and change it to "callbacks"

do it for index.es.js as well

**Comment by GabeEddyT** [comment]
Sorry about the regression. I overlooked it when merging @krisb's changes.
